test:
  message: "Hello world from the user service cfg file!"

server:
  port: 8100

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
      client:
        provider:
          platform-auth-server:
            issuer-uri: http://127.0.0.1:9000
        registration:
          gateway-client:
            provider: platform-auth-server
            client-id: gateway-client
            client-secret: gateway-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8100/login/oauth2/code/gateway-client
            scope:
              - openid
              - profile
              - email
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/userservice/**
          filters:
            - StripPrefix=1
            - TokenRelay

        - id: deck-service
          uri: lb://DECKSERVICE
          predicates:
            - Path=/deckservice/**
          filters:
            - StripPrefix=1

        - id: game-service
          uri: lb://GAMESERVICE
          predicates:
            - Path=/gameservice/**
          filters:
            - StripPrefix=1
            - TokenRelay

        - id: chat-service
          uri: lb://CHATSERVICE
          predicates:
            - Path=/chatservice/**
          filters:
            - StripPrefix=1
            - TokenRelay

        - id: chat-websocket
          uri: lb://CHATSERVICE
          predicates:
            - Path=/ws-chat/**

        - id: ai-service
          uri: lb://AISERVICE
          predicates:
            - Path=/aiservice/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: TRACE

# * turn off the discovery client for testing purposes
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false