test:
  message: "Hello world from the user service cfg file!"

server:
  port: 8100

spring:
  security:
    oauth2:
      client:
        provider:
          platform-auth-server:
            issuer-uri: http://127.0.0.1:9000
        registration:
          gateway-client:
            provider: platform-auth-server
            client-id: gateway-client
            client-secret: gateway-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8100/login/oauth2/code/gateway-client
            scope:
              - openid
              - profile
              - email
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/userservice/**
          filters:
            - StripPrefix=1
#            For authentication
            - TokenRelay

        - id: deck-service
          uri: lb://DECKSERVICE
          predicates:
            - Path=/deckservice/**
          filters:
            - StripPrefix=1

        - id: game-service
          uri: lb://GAMESERVICE
          predicates:
            - Path=/gameservice/**
          filters:
            - StripPrefix=1
            - TokenRelay

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173" # frontend origin
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - DELETE
            allowedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

# * turn off the discovery client for testing purposes
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false