test:
  message: "Hello world from the deck service cfg file!"

server:
  port: 8105

spring:
  config:
    import: dbconnection.yml

# * turn off the discovery client for testing purposes
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false