test:
  message: "Hello world from the deck service cfg file!"

server:
  port: 8101

spring:
  config:
    import: dbconnection.yml

deck:
  api:
    url: https://deckofcardsapi.com/api/deck/
#! turn off the discovery client for testing purposes
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false