test:
  message: "Hello world from the deck service cfg file!"

server:
  port: 8104

spring:
  config:
    import: dbconnection.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000


# * turn off the discovery client for testing purposes
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false