test:
  message: "Hello world from the user service cfg file!"

server:
  port: 8102

springdoc:
    api-docs:
      path: /api-docs

spring:
  config:
    import: dbconnection.yml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000

# * turn off the discovery client for testing purposes
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false