name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: dealmatedb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: "24"
          distribution: "oracle"

      - name: Build and run Discovery Server
        run: |
          mvn -f dealmate-project/discovery-server/pom.xml spring-boot:run &
          sleep 20

      - name: Build and run Config Server
        run: |
          mvn -f dealmate-project/config-server/pom.xml spring-boot:run &
          sleep 20

      - name: Build and run Auth Server
        run: |
          mvn -f dealmate-project/auth-server/pom.xml spring-boot:run &
          sleep 20

      - name: Build and run API Gateway
        run: |
          mvn -f dealmate-project/api-gateway/pom.xml spring-boot:run &
          sleep 20

      - name: Build User Service
        run: |
          mvn -f dealmate-project/user-service clean install

      - name: Build Deck Service
        run: |
          mvn -f dealmate-project/deck-service clean install

      - name: Build Game Service
        run: |
          mvn -f dealmate-project/game-service clean install
#
#      - name: Build Chat Service
#        run: |
#          mvn -f dealmate-project/chat-service clean install
#
#      - name: Build AI Service
#        run: |
#          mvn -f dealmate-project/ai-service clean install

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
